export const ENHANCED_STYLES = `
/* Shared Classic/Enhanced risk treatment: opaque fills and bold contrasting labels. */
.risk-high{background:rgba(180,35,56,.7)!important;color:#102e3d!important}
.risk-medium{background:rgba(244,189,66,.7)!important;color:#352400!important}
.risk-low{background:rgba(24,116,84,.7)!important;color:#102e3d!important}
.risk-not-rated{background:rgba(214,223,229,.7)!important;color:#273d4b!important}
.inline-select[class*="risk-"],.risk-pill{font-weight:850!important;border:1px solid rgba(0,0,0,.16);opacity:1}
.inline-select[class*="risk-"]:hover{filter:none}
.inline-select.risk-high:hover{background:rgba(180,35,56,.7)!important}.inline-select.risk-medium:hover{background:rgba(244,189,66,.7)!important}.inline-select.risk-low:hover{background:rgba(24,116,84,.7)!important}.inline-select.risk-not-rated:hover{background:rgba(214,223,229,.7)!important}
.inline-select option{background:#fff;color:#23313a}
.en-experience,.en-layouts{display:inline-flex;background:#e8eff3;border:1px solid #cbdbe4;padding:3px;border-radius:9px;gap:3px}
.en-experience button,.en-layouts button{border:0;border-radius:6px;background:transparent;color:#415e6d;font-size:calc(12.0px + var(--en-font-adjust,0pt));font-weight:750;padding:8px 12px;cursor:pointer}
.en-experience button[aria-pressed="true"],.en-layouts button[aria-pressed="true"]{background:#063450;color:white;box-shadow:0 2px 4px #06345022}
.is-enhanced{background:#eaf0f3}
.en-toolbar{background:#fff;border:1px solid #d6e1e7;border-radius:13px;margin-bottom:14px;box-shadow:0 4px 20px #06345005;overflow:hidden}
.en-toolbar-top{padding:14px 16px;display:flex;flex-wrap:wrap;align-items:center;gap:12px}.en-toolbar-top>div:first-child{margin-right:auto}.en-toolbar-top strong{display:block;color:#123b50;font-size:calc(16.0px + var(--en-font-adjust,0pt));margin-top:3px}.en-eyebrow{font-size:calc(10.0px + var(--en-font-adjust,0pt));letter-spacing:.07em;text-transform:uppercase;font-weight:800;color:#24728e}.en-sort-label{display:grid;gap:4px;font-size:calc(10.0px + var(--en-font-adjust,0pt));font-weight:700;color:#526b79}.en-sort-label select{border:1px solid #ccd9e0;border-radius:6px;padding:6px 8px;background:#fff;font-size:calc(12.0px + var(--en-font-adjust,0pt));color:#233e4e}
.en-navigator{background:#f7fafb;border-top:1px solid #e0e8ed;display:flex;align-items:center;gap:16px;padding:10px 16px;flex-wrap:wrap}.en-nav-buttons{display:flex;gap:7px;align-items:center;flex-shrink:0;color:#496371;font-size:calc(12.0px + var(--en-font-adjust,0pt))}.en-nav-buttons label{display:flex;align-items:center;gap:6px}.en-nav-buttons input{width:57px;border:1px solid #c4d5de;border-radius:6px;background:white;padding:5px;color:#123b50}.en-nav-buttons .btn{min-width:31px;padding:5px 8px;font-size:calc(16.0px + var(--en-font-adjust,0pt))}.en-nav-title{font-size:calc(12.0px + var(--en-font-adjust,0pt));color:#274d62;flex:1;min-width:140px;font-weight:650}.en-slider{width:180px;accent-color:#087e9c}.en-rolodex{border-left:6px solid #087e9c}.en-rolodex .en-nav-title{border:1px solid #c4d5de;border-radius:8px 8px 2px 2px;background:#fff;padding:10px;max-width:360px}
.en-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.en-card{background:#fff;border:1px solid #d5e0e6;border-radius:14px;overflow:hidden;box-shadow:0 5px 18px #06345007;display:flex;flex-direction:column}.en-card.is-selected{outline:2px solid #1586a1;outline-offset:2px}.en-photo{margin:0;background:#e5edf1;position:relative}.en-photo img{width:100%;height:190px;object-fit:contain;display:block;background:#dce6eb}.en-photo figcaption{background:#f4f8fa;color:#455f6e;font-size:calc(10.0px + var(--en-font-adjust,0pt));line-height:1.4;padding:8px 12px}.en-photo figcaption span{display:block}.en-photo figcaption a{color:#086785}.en-photo-placeholder{min-height:238px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;gap:8px;padding:24px;background:linear-gradient(140deg,#dce9ed,#edf3f5);color:#426678}.en-photo-placeholder>span{font-size:calc(35.0px + var(--en-font-adjust,0pt));font-weight:400;border:1px solid #a9c2ce;border-radius:50%;width:52px;height:52px;line-height:50px}.en-photo-placeholder strong{font-size:calc(14.0px + var(--en-font-adjust,0pt));max-width:90%}.en-photo-placeholder small{color:#607d8b;font-size:calc(11.0px + var(--en-font-adjust,0pt))}.en-card-body{padding:18px;display:flex;flex-direction:column;flex:1}.en-card h3{margin:7px 0 12px;font-size:calc(19.0px + var(--en-font-adjust,0pt));line-height:1.3}.en-card h3 button{font:inherit;font-weight:750;text-align:left;background:none;border:0;color:#0a3a51;padding:0;cursor:pointer}.en-card-update{font-size:calc(13.0px + var(--en-font-adjust,0pt));line-height:1.6;color:#496270;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;margin:14px 0}.en-card-meta{display:flex;gap:10px;justify-content:space-between;font-size:calc(11.0px + var(--en-font-adjust,0pt));color:#607987;border-top:1px solid #e8eef1;padding:12px 0;flex-wrap:wrap;margin-top:auto}.en-open{align-self:flex-start;color:#086580;background:#f2f9fb;border-color:#c4e0e9;font-size:calc(12.0px + var(--en-font-adjust,0pt))}.en-open span{margin-left:15px}.en-risk-pair{display:flex;gap:12px;flex-wrap:wrap}.en-risk-pair>span{display:flex;align-items:center;gap:6px;font-size:calc(11.0px + var(--en-font-adjust,0pt));color:#516976;font-weight:650}.en-risk-pair .risk-pill{font-size:calc(11.0px + var(--en-font-adjust,0pt));padding:5px 10px}
.en-record{border:1px solid #d4e0e7;background:#fff;border-radius:15px;overflow:hidden}.en-record-hero{display:grid;grid-template-columns:minmax(260px,.85fr) minmax(0,1.3fr)}.en-record-hero .en-photo{display:flex;flex-direction:column}.en-record-hero .en-photo img{height:310px;flex:1;min-height:200px;max-height:410px}.en-record-hero .en-photo-placeholder{flex:1;min-height:320px}.en-record-identity{padding:26px 30px}.en-record h2{font-size:calc(29.0px + var(--en-font-adjust,0pt));line-height:1.15;letter-spacing:-.025em;color:#09384f;margin:8px 0 18px}.en-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px 20px;margin:22px 0}.en-facts dt{font-size:calc(10.0px + var(--en-font-adjust,0pt));color:#587581;text-transform:uppercase;letter-spacing:.045em;margin-bottom:5px}.en-facts dd{margin:0;font-size:calc(14.0px + var(--en-font-adjust,0pt));font-weight:650;color:#173b50;overflow-wrap:anywhere}.en-record-actions{display:flex;gap:8px;flex-wrap:wrap}.en-record-body{padding:26px 30px;border-top:1px solid #e0e8ed;display:grid;grid-template-columns:1fr 1fr;gap:26px}.en-record-body section{min-width:0}.en-record-body h3{font-size:calc(15.0px + var(--en-font-adjust,0pt));color:#0d4259;margin:0 0 12px}.en-record-body p{font-size:calc(14.0px + var(--en-font-adjust,0pt));line-height:1.7;white-space:pre-wrap;margin:8px 0;color:#304f60;overflow-wrap:anywhere}.en-update,.en-history-section{grid-column:1/-1}.en-update{background:#f0f7fa;border-left:4px solid #148aa7;border-radius:5px;padding:20px 24px}.en-section-heading{display:flex;align-items:center;justify-content:space-between;gap:14px}.en-section-heading>span{font-size:calc(12.0px + var(--en-font-adjust,0pt));color:#386779}.en-section-heading h3{margin-bottom:0}.en-history-item{border-top:1px solid #e1e9ed;padding:14px 0}.en-history-item strong{font-size:calc(13.0px + var(--en-font-adjust,0pt));color:#086682}.en-history-item small{margin-left:12px;font-size:calc(11.0px + var(--en-font-adjust,0pt));color:#526e7d}.en-empty{padding:60px 25px;text-align:center;background:#fff;border:1px dashed #adc4d0;border-radius:13px}.en-empty h2{font-size:calc(22.0px + var(--en-font-adjust,0pt));color:#1b4b62}.en-empty p,.en-muted,.en-photo-note{color:#587281;font-size:calc(12.0px + var(--en-font-adjust,0pt));line-height:1.5}.en-collage{grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.en-collage .en-card h3{font-size:calc(16.0px + var(--en-font-adjust,0pt))}.en-collage .en-card-body{padding:14px}.en-collage .en-photo-placeholder{min-height:230px}.en-selected-row td{background:#eaf6fa!important;border-bottom-color:#93cbd9}.is-enhanced .activity-inline{max-height:160px}.is-enhanced .activity-hint{color:#536d7b}
.en-meeting .en-record-body p{font-size:calc(20.0px + var(--en-font-adjust,0pt));line-height:1.75}.en-meeting .en-record h2{font-size:calc(34.0px + var(--en-font-adjust,0pt))}.en-meeting .en-record-body h3{font-size:calc(19.0px + var(--en-font-adjust,0pt))}.en-meeting td,.en-meeting .project-link,.en-meeting .activity-inline{font-size:calc(16.0px + var(--en-font-adjust,0pt))}.en-meeting .activity-inline{max-height:none}.en-meeting .en-card-update{font-size:calc(17.0px + var(--en-font-adjust,0pt));-webkit-line-clamp:6}.en-meeting .en-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.en-meeting .en-record-hero{grid-template-columns:.65fr 1.35fr}
.en-toolbar button:focus-visible,.en-card button:focus-visible,.en-experience button:focus-visible{outline:3px solid #0c8bac;outline-offset:3px}button:disabled{cursor:not-allowed;opacity:.45}
@media(max-width:1250px){.en-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.en-collage{grid-template-columns:repeat(3,minmax(0,1fr))}.en-record-identity{padding:22px}.en-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.is-enhanced .topbar{flex-wrap:wrap}.en-record h2{font-size:calc(25.0px + var(--en-font-adjust,0pt))}}
@media(max-width:760px){.en-record-hero,.en-record-body,.en-meeting .en-record-hero{grid-template-columns:1fr}.en-grid,.en-collage,.en-meeting .en-grid{grid-template-columns:1fr}.en-toolbar-top{gap:9px}.en-layouts{width:100%;justify-content:space-between}.en-record-body{padding:18px}.en-record-hero .en-photo img{max-height:230px}.en-nav-title{flex-basis:100%}.en-risk-pair{gap:8px}.en-experience button{padding:7px 10px}.en-meeting td{font-size:calc(12.0px + var(--en-font-adjust,0pt))}}

/* Revision 2: shared sidebar, selectable record navigator, frozen list workspace. */
.sidebar{overflow-y:auto}.nav{min-width:0}.en-rolodex-widget{min-width:0;width:100%;max-width:100%}.en-ro-inner>div{min-width:0}.sidebar>.nav{flex-shrink:0}
.en-experience{margin-top:auto;padding:12px 0 0;display:block;background:none;border:0;border-radius:0;flex-shrink:0}
.en-experience .nav-btn{width:100%;background:#0c5871;color:white;border:1px solid #398297;padding:11px 9px;font-size:calc(13.0px + var(--en-font-adjust,0pt))}.en-experience .nav-icon{font-size:calc(19.0px + var(--en-font-adjust,0pt))}
.en-nav-picker{position:relative;flex:0 0 34px}.en-nav-picker>button{width:34px;height:34px;padding:5px;color:#416577;background:#fff;border:1px solid #c5d6df;border-radius:7px}.en-nav-picker svg{width:23px;height:23px}
.en-nav-menu{position:absolute;top:42px;right:0;z-index:60;min-width:210px;padding:6px;background:white;border:1px solid #bfd1dc;border-radius:9px;box-shadow:0 8px 25px #06345033}.en-nav-menu button{display:block;width:100%;border:0;background:white;text-align:left;padding:10px;font-size:calc(12.0px + var(--en-font-adjust,0pt));color:#063450;border-radius:5px}.en-nav-menu button[aria-pressed=true]{background:#def0f6;font-weight:800}
.en-rolodex-widget{margin:5px 0 9px;padding:11px;background:linear-gradient(135deg,#f3f5f6,#d1dae0);border:3px outset #e1e6e9;box-shadow:3px 4px 0 #001d2b;color:#173749;text-align:center;border-radius:3px}.en-rolodex-widget h3{font-size:calc(12.0px + var(--en-font-adjust,0pt));font-weight:650;margin:0 0 8px}.en-ro-inner{display:grid;grid-template-columns:minmax(0,1fr) 27px;gap:9px}.en-book{position:relative;display:block;width:100%;height:108px;border:3px outset #bfcbd2;background:linear-gradient(#fff 0 48%,#bbc5ca 48% 53%,#fff 53%);box-shadow:4px 4px 0 #8e9ba4;cursor:pointer;color:#1498df}.en-book:before{content:'≡';position:absolute;font-size:calc(39.0px + var(--en-font-adjust,0pt));line-height:35px;top:2px;left:24%;right:24%;border-bottom:0}.en-book:after{content:'∩ ∩ ∩';position:absolute;top:43%;left:0;right:0;color:#294657;font-size:calc(23.0px + var(--en-font-adjust,0pt));text-shadow:1px 1px white}.en-book:active{transform:rotateX(12deg);filter:brightness(.92)}
.en-ro-track{display:flex;flex-direction:column;align-items:center;gap:2px}.en-ro-track button{padding:0;width:25px;height:22px;border:1px solid #97aab5;background:#fff;color:#153f56}.en-ro-track input{writing-mode:vertical-lr;direction:ltr;width:23px;height:112px;margin:0;appearance:none;background:white;border:1px inset #b9c6ce;border-radius:10px;cursor:pointer}
.en-ro-track input::-webkit-slider-thumb{appearance:none;width:20px;height:25px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#7fe8ff,#008cf0 55%,#004dac);border:1px solid #0057a8;box-shadow:1px 1px 2px #537c9b}.en-ro-track input::-moz-range-thumb{width:18px;height:23px;border-radius:50%;background:#008cf0;border:1px solid #0057a8}
.en-ro-number{margin-top:10px;width:100%;min-width:0;text-align:center;border:1px inset #adb9c1;padding:3px;font-size:calc(13.0px + var(--en-font-adjust,0pt))}.en-ro-count{font-size:calc(11.0px + var(--en-font-adjust,0pt));margin:8px 0 0}.en-ro-name{font-size:calc(10.0px + var(--en-font-adjust,0pt));margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.en-pagination{display:flex;align-items:center;gap:10px;width:100%}.en-pagination input[type=range]{flex:1;min-width:40px;accent-color:#078cde;cursor:pointer}.en-pagination input[type=number]{width:58px;padding:4px;border:1px solid #c4d5de;border-radius:5px}.en-pagination span{white-space:nowrap;font-size:calc(12.0px + var(--en-font-adjust,0pt));color:#34586b}.en-pagination button{padding:5px 10px}.en-bottom-nav{position:fixed;bottom:0;right:0;z-index:35;background:#f7fafb;border-top:1px solid #c5d5de;padding:10px 18px;box-shadow:0 -3px 14px #06345012}.has-bottom-nav main{padding-bottom:58px}
.instant-tooltip:before{content:'';position:absolute;top:-6px;left:var(--tip-pointer,50%);width:10px;height:10px;background:var(--navy2);border-left:1px solid #315970;border-top:1px solid #315970;transform:translateX(-50%) rotate(45deg)}.instant-tooltip[data-side=above]:before{top:auto;bottom:-6px;transform:translateX(-50%) rotate(225deg)}
.freeze-list .app{height:100dvh;min-height:0;overflow:hidden}.freeze-list main{height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden}.freeze-list .topbar{flex-shrink:0}.freeze-list .content{flex:1;min-height:0;display:flex;flex-direction:column;padding-bottom:12px}.freeze-list #workspace{flex:1;min-height:0;display:flex;flex-direction:column}.freeze-list .unit-switcher,.freeze-list .en-toolbar,.freeze-list .table-caption,.freeze-list .compact-kpis{flex-shrink:0}.freeze-list .pane:not([hidden]){flex:1;min-height:0;display:flex;flex-direction:column}.freeze-list .card.workspace{flex:1;min-height:0;display:flex;flex-direction:column}.freeze-list .table-wrap{flex:1;min-height:0;overflow:auto;max-height:none}.freeze-list .table-wrap th{position:sticky;top:0;z-index:5;background:#f7fafb;box-shadow:0 1px 0 #bccfd9}.freeze-list .en-panel:not([hidden]){flex:1;min-height:0;overflow:auto;overscroll-behavior:contain}.freeze-list .en-panel[hidden],.freeze-list .card.workspace[hidden]{display:none}
@media(min-width:741px) and (max-width:1180px){.en-rolodex-widget{padding:4px;border-width:2px}.en-rolodex-widget h3,.en-ro-name{display:none}.en-ro-inner{grid-template-columns:1fr;gap:3px}.en-book{height:63px}.en-book:after{font-size:calc(15.0px + var(--en-font-adjust,0pt))}.en-book:before{font-size:calc(28.0px + var(--en-font-adjust,0pt));top:-2px}.en-ro-track{display:none}.en-ro-number{font-size:calc(10.0px + var(--en-font-adjust,0pt));padding:1px;margin-top:8px}.en-ro-count{font-size:calc(9.0px + var(--en-font-adjust,0pt))}.en-experience .nav-btn{padding:9px 3px}}
@media(max-width:740px){.freeze-list .app{display:flex;flex-direction:column}.freeze-list main{height:auto;flex:1}.freeze-list .sidebar{flex-shrink:0}.en-experience{margin-top:7px;padding:0}.en-experience .nav-btn{width:auto}.en-rolodex-widget{min-width:130px;width:130px;flex-shrink:0;margin:0 8px}.en-rolodex-widget h3,.en-ro-name{display:none}.en-book{height:68px}.en-book:before{font-size:calc(26.0px + var(--en-font-adjust,0pt))}.en-book:after{font-size:calc(16.0px + var(--en-font-adjust,0pt))}.en-ro-track input{height:50px}.en-ro-number{margin-top:5px}.en-ro-count{font-size:calc(9.0px + var(--en-font-adjust,0pt))}.en-ro-track button{height:17px}.en-bottom-nav{padding:8px}.en-pagination{gap:4px}.en-pagination span{font-size:calc(10.0px + var(--en-font-adjust,0pt))}.en-pagination input[type=number]{width:43px}.freeze-list .sidebar{max-height:130px;overflow:auto}.freeze-list .content{overflow:auto}.freeze-list .card.workspace{min-height:180px}.freeze-list .compact-kpis{display:none}}


.instant-tooltip{pointer-events:none}
/* Revision 3: smaller centered mechanical Rolodex and destination text switch. */
.risk-high,.risk-low{color:#fff!important}
.en-experience #enToggle,.en-experience #enToggle:hover{background:transparent;border:0;box-shadow:none;color:#f2b134;font-size:calc(10.333px + var(--en-font-adjust,0pt));font-weight:750;padding:8px 9px;width:auto;border-radius:0;min-width:0}
.en-rolodex-widget{zoom:.7;width:70%;justify-self:center;margin:7px auto 13px;background:linear-gradient(135deg,#f3f3f3 0%,#d2d2d2 48%,#eee 100%);border:7px ridge #dfdfdf;box-shadow:5px 6px 0 #737c81,8px 9px 7px #00192599;border-radius:0;padding:11px;color:#20292f}
.en-ro-inner{padding:5px;background:linear-gradient(120deg,#b4b4b4,#f7f7f7 40%,#c5c5c5);border:3px inset #dfdfdf;gap:9px}
.en-book{height:108px;border:0;background:transparent;box-shadow:3px 4px 3px #4447;cursor:default;transform:none!important;filter:none!important}
.en-book:before,.en-book:after{display:none}.en-book svg{display:block;width:100%;height:100%;pointer-events:none}
.en-book-half{position:absolute;left:0;width:100%;height:50%;padding:0;border:0;background:transparent;cursor:pointer;border-radius:0;box-shadow:none}.en-book-back{top:0}.en-book-forward{bottom:0}.en-book-half:hover:not(:disabled){background:#008cff0c}.en-book-half:active:not(:disabled){background:#00395824}.en-book-half:focus-visible{outline:3px solid #078cca;outline-offset:-3px}.en-book-half:disabled{opacity:1;cursor:default}
.en-ro-track input{background:linear-gradient(90deg,#a0a0a0,#fff 45%,#d6d6d6);box-shadow:inset 1px 1px 3px #3337;border-color:#777}.en-ro-track button{background:linear-gradient(#fff,#dedede);border:2px outset #eee;color:#111}.en-ro-number{background:white;color:#111;box-shadow:inset 1px 1px 2px #7776}.en-ro-count{font-size:calc(12.0px + var(--en-font-adjust,0pt))}
@media(min-width:741px) and (max-width:1180px){.en-rolodex-widget{border-width:3px;padding:4px}.en-ro-inner{padding:1px;border-width:1px}.en-book{height:63px}.en-experience #enToggle{padding:8px 0;font-size:calc(10.333px + var(--en-font-adjust,0pt))}}
@media(max-width:740px){.en-book{height:68px}.en-rolodex-widget{margin:0 8px;border-width:4px}}


/* Revision 4: liquid aqua control and directional card turns. */
.en-experience{display:flex;justify-content:center}.en-experience #enToggle{display:inline-flex;align-items:center;justify-content:center;gap:7px}.en-experience #enToggle span{display:inline}.en-experience #enToggle .en-switch-arrows{font-size:calc(16.0px + var(--en-font-adjust,0pt));line-height:1}
.en-ro-track input::-webkit-slider-thumb{width:21px;height:26px;border-radius:48%;border:1px solid #00518f;background:radial-gradient(ellipse at 31% 20%,#f4ffff 0%,#b6f5ff 7%,#38cefa99 16%,transparent 30%),radial-gradient(ellipse at 68% 75%,#00c8f599 0%,transparent 31%),radial-gradient(ellipse at 39% 24%,#159deb 0%,#0562d5 39%,#033b9f 70%,#00164f 100%);box-shadow:inset 1px 1px 2px #a5efffbb,inset -2px -3px 4px #000f5599,2px 3px 3px #101f5180}
.en-ro-track input::-moz-range-thumb{width:19px;height:24px;border-radius:48%;border:1px solid #00518f;background:radial-gradient(ellipse at 31% 20%,#f4ffff 0%,#b6f5ff 7%,#38cefa99 16%,transparent 30%),radial-gradient(ellipse at 68% 75%,#00c8f599 0%,transparent 31%),radial-gradient(ellipse at 39% 24%,#159deb 0%,#0562d5 39%,#033b9f 70%,#00164f 100%);box-shadow:inset 1px 1px 2px #a5efffbb,inset -2px -3px 4px #000f5599,2px 3px 3px #101f5180}
.en-book{perspective:380px;isolation:isolate}.en-first-record .en-upper-paper,.en-last-record .en-lower-paper{fill:#b4b4b4;stroke:#b4b4b4}.en-first-record .en-upper-lines,.en-last-record .en-lower-lines{display:none}
.en-flipping-card{position:absolute;left:7%;width:79%;height:40%;background:linear-gradient(#fff,#eee 68%,#c4c4c4);border:1px solid #888;box-shadow:2px 2px 3px #3337;z-index:3;pointer-events:none;transform-style:preserve-3d;backface-visibility:visible;padding:8% 12%}.en-flip-forward{top:52%;transform-origin:50% 0}.en-flip-back{top:12%;transform-origin:50% 100%}.en-flipping-card i{display:block;height:2px;background:#32bafd;margin-bottom:5px;border-radius:2px}.en-flipping-card i:first-child{width:65%}.en-flipping-card i:last-child{width:85%}
@media(prefers-reduced-motion:reduce){.en-flipping-card{display:none}}

/* Revision 5: consistent upper-left illumination and fuller card proportions. */
.en-rolodex-widget{background:linear-gradient(155deg,#eeeeec,#d7d9da 55%,#b9bec2);border-color:#d7dadc;box-shadow:2px 3px 0 #747d83,4px 6px 4px #00152180,inset 1px 1px 1px #ffffffb3}
.en-ro-inner{background:linear-gradient(155deg,#b0b5b9,#d0d3d5 45%,#c2c6c9);box-shadow:inset 2px 2px 4px #343d4340,inset -1px -1px 1px #ffffffa6}
.en-book{box-shadow:2px 3px 2px #242d3566,3px 5px 4px #17222b33}
.en-first-record .en-upper-paper,.en-last-record .en-lower-paper{fill:url(#enPlastic);stroke:#92999e}
.en-ro-track input{background:linear-gradient(90deg,#8d969f,#dbe0e4 55%,#afb8c0);box-shadow:inset 2px 2px 3px #26334070,inset -1px 0 1px #fff8}
.en-ro-number{box-shadow:inset 1px 2px 2px #36424b40;border-color:#929da4}
@media(min-width:1181px){.en-book{height:128px}.en-ro-number{margin-top:12px}}
/* Revision 9: restore the earlier crisp beveled frame and offset shadows. */
.en-rolodex-widget{background:linear-gradient(135deg,#f3f3f3 0%,#d2d2d2 48%,#eee 100%);border:7px ridge #dfdfdf;box-shadow:5px 6px 0 #737c81,8px 9px 7px #00192599}
.en-ro-inner{background:linear-gradient(120deg,#b4b4b4,#f7f7f7 40%,#c5c5c5);border:3px inset #dfdfdf;box-shadow:none}
.en-book{box-shadow:3px 4px 3px #4447}
.en-upper-paper,.en-lower-paper{filter:none}
.en-ro-track input{background:linear-gradient(90deg,#a0a0a0,#fff 45%,#d6d6d6);box-shadow:inset 1px 1px 3px #3337;border-color:#777}
.en-ro-track button{background:linear-gradient(#fff,#dedede);border:2px outset #eee;box-shadow:none}
.en-ro-number{border:1px inset #adb9c1;box-shadow:inset 1px 1px 2px #7776}
@media(min-width:741px) and (max-width:1180px){.en-rolodex-widget{border-width:3px}.en-ro-inner{border-width:1px}}
@media(max-width:740px){.en-rolodex-widget{border-width:4px}}

.en-history-controls{display:inline-flex;align-items:center;gap:8px}.en-lock{display:inline-flex;color:#777;cursor:help}.en-lock svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:1.8;opacity:.45}.en-history-item p,.en-compare p,.en-update p{white-space:pre-wrap}.en-compare{display:grid;grid-template-columns:1fr 1fr;gap:16px}.en-compare section{border:1px solid #d3dfe5;padding:16px;border-radius:8px;background:#f8fafb}.en-compare select,.en-weekly select{padding:8px;border:1px solid #b7ccd7;border-radius:6px;background:white;color:#163e51}.en-compare-section,.en-weekly{grid-column:1/-1}.en-week-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,260px),1fr));gap:16px;margin-top:16px}.en-week-grid figure{margin:0;background:#f4f8fa;border:1px solid #d4dfe5;border-radius:10px;overflow:hidden}.en-week-grid img{display:block;width:100%;height:300px;object-fit:contain;background:#eef2f4}.en-week-grid a{display:block}.en-week-grid figcaption{overflow-wrap:anywhere}.en-sort-label select{position:relative;top:-3px}[data-en-photo-mode][aria-pressed="true"]{background:#06394f;color:white;border-color:#06394f}.en-week-grid figcaption{padding:12px}.en-empty-photo{text-align:center;background:#f2f6f8;border:1px dashed #a9beca;padding:32px}.en-empty-photo>span{font-size:calc(40.0px + var(--en-font-adjust,0pt));color:#7996a6}.en-workflow-dialog{width:min(650px,92vw);max-height:90vh;border:1px solid #b7ccd7;border-radius:14px;padding:25px;color:#153c50}.en-workflow-dialog::backdrop{background:#00263788}.en-workflow-dialog label{display:grid;gap:8px;margin:16px 0}.en-workflow-dialog input,.en-workflow-dialog textarea{padding:10px;font:inherit;border:1px solid #b7ccd7;border-radius:6px}.en-workflow-dialog textarea{width:100%;box-sizing:border-box}.en-upload-preview{display:flex;gap:10px;flex-wrap:wrap}.en-upload-preview img{max-width:150px;max-height:130px;object-fit:contain}.en-form-error{color:#a62036}.en-revision{border-left:3px solid #bdcbd3;padding-left:12px;margin:12px 0}.en-weekly{background:white;padding:20px;border-radius:12px}.en-history-item small{display:block}.en-compare p{line-height:1.6}.en-workflow-dialog h2{margin-top:0}
@media(max-width:700px){.en-compare{grid-template-columns:1fr}}

/* Revision 11: bounded editable text prevents paint spilling into adjacent records. */
.activity-inline,.activity-inline:focus,.is-enhanced .activity-inline,.development-table .activity-inline,.en-meeting .activity-inline{max-height:240px!important;overflow:auto!important;position:relative;display:block;overflow-wrap:anywhere;white-space:pre-wrap;margin:0;width:100%}
.risk-high,.inline-select.risk-high:hover{background:#b42338!important;color:#fff!important}.risk-low,.inline-select.risk-low:hover{background:#187454!important;color:#fff!important}.risk-medium,.inline-select.risk-medium:hover{background:#f4bd42!important;color:#352400!important}.risk-not-rated{background:#d6dfe5!important;color:#273d4b!important}
.en-update textarea{display:block;width:100%;box-sizing:border-box;font:inherit;line-height:1.6;color:#304f60;border:1px solid #b9cdd7;border-radius:7px;padding:12px;margin:14px 0;resize:vertical;min-height:130px}.en-update textarea[readonly]{background:#f8fbfc}.en-update input[type=date]{padding:8px;border:1px solid #b9cdd7;border-radius:6px}.en-update .en-record-actions{align-items:center}.en-update small{color:#58717e}.en-dropzone{margin:14px 0;padding:24px;border:2px dashed #8fb1c3;border-radius:9px;background:#f3f9fc;text-align:center}.en-dropzone small{display:block;margin-top:10px}.en-dragging{outline:3px dashed #0985b3;background:#e8f6fc}.en-inline-save{margin-top:5px}.en-property{white-space:normal;line-height:1.3}button:disabled{cursor:not-allowed}
.en-meeting .en-update textarea{font-size:calc(20.0px + var(--en-font-adjust,0pt));line-height:1.75}
html{font-size:calc(16.0px + var(--en-font-adjust,0pt))}

.en-experience #enToggle,.en-experience #enToggle:hover{font-size:calc(13px + var(--en-font-adjust,0pt))}
.en-font-controls{display:flex;gap:0;align-items:center;flex-shrink:0}.en-font-controls button{height:34px;min-width:21px;border:0;background:transparent;color:#365e72;font-weight:400;cursor:pointer;padding:2px 2px}.en-font-controls .en-small-a{font-size:14px}.en-font-controls .en-large-a{font-size:21px}.en-font-controls button:hover{background:#e8f3f8;border-radius:5px}.en-font-controls button:disabled{opacity:.35}

/* Dedicated photo register: fixed controls, scrolling data, touch-friendly forms. */
[data-pane="photos"]{min-height:0;gap:16px}
.photo-filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin-top:14px}
.photo-filters label{display:grid;gap:5px;flex:1;min-width:150px;font-size:12px;font-weight:600}
.photo-filters select,.photo-filters input{width:100%;min-height:42px;max-width:100%;border:1px solid #c9dce7;border-radius:8px;padding:8px 10px;background:#fff;color:#23475b;font:inherit}.photo-filters{padding:0 16px 16px}.photo-filters label{color:#486477}
.photo-picker{width:44px;height:44px;padding:7px}.photo-picker svg{width:28px;height:28px}
.photo-content{padding:16px;background:#fff;border:1px solid #d5e2e9;border-radius:12px}
.photo-record{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:28px}
.photo-record figure{margin:0;align-self:start}.photo-record img{width:100%;max-height:65vh;object-fit:contain;background:#f1f4f5}
.photo-record figcaption{padding:12px;color:#567}.photo-details>div{display:grid;grid-template-columns:145px 1fr;gap:16px;padding:12px 0;border-bottom:1px solid #dde5e8}
.photo-details dt{font-weight:700}.photo-details dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}
.photo-collage{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}
.photo-tile{border:1px solid #d5e2e9;border-radius:8px;overflow:hidden;background:#f6f8fa;color:#123b4f;padding:0;text-align:left;cursor:pointer}
.photo-tile img{width:100%;height:180px;object-fit:contain}.photo-tile span{display:grid;gap:5px;padding:12px}.photo-tile small{color:#567}
.photo-table{min-width:920px}.photo-table th{position:sticky;top:0;background:#f2f7f9;z-index:1}.photo-table p{margin:6px 0;max-width:320px;white-space:pre-wrap}.photo-selected{background:#e2f3fa}
.photo-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.photo-fields label{min-width:0}.photo-wide{grid-column:1/-1}.photo-fields input,.photo-fields textarea{width:100%}.photo-check{display:flex!important;align-items:center;gap:8px}.photo-check input{width:auto}
.photo-upload-actions{display:flex;gap:16px;flex-wrap:wrap;margin-top:18px}.photo-upload-actions label{display:block;min-height:44px;max-width:100%}.photo-upload-actions input{display:block;width:100%;max-width:250px;margin-top:8px}
.photo-notice{padding:24px}.photo-content .en-empty{padding:40px 16px}
.freeze-list [data-pane="photos"]:not([hidden]){display:flex;flex-direction:column;flex:1;min-height:0}
.freeze-list [data-pane="photos"] .photo-content{flex:1;overflow:auto;min-height:0}
@media(max-width:900px){.photo-record{grid-template-columns:1fr}.photo-record img{max-height:45vh}.photo-details>div{grid-template-columns:120px 1fr}.photo-filters{gap:8px}.photo-fields{grid-template-columns:1fr}.photo-wide{grid-column:auto}}

.en-attachment-drop{border:2px dashed #88b8cc;border-radius:14px;padding:24px 16px;text-align:center;background:#f3fafd;cursor:pointer;display:grid;gap:8px;margin:14px 0;color:#124f6a}.en-attachment-drop span{font-size:13px;color:#526f7f}.en-attachment-drop:focus-visible{outline:3px solid #078ccc}.en-attachment-drop.is-dragging,.en-file-hover{outline:3px solid #078ccc!important;background:#d9f3fc!important}
.en-rolodex-widget h3{font-size:calc(12px + 1pt + var(--en-font-adjust,0pt))}.en-ro-number{font-size:calc(13px + 1pt + var(--en-font-adjust,0pt))}.en-ro-count{font-size:calc(12px + 1pt + var(--en-font-adjust,0pt))}.en-ro-name{font-size:calc(10px + 1pt + var(--en-font-adjust,0pt))}
@media(min-width:741px) and (max-width:1180px){.en-ro-number{font-size:calc(10px + 1pt + var(--en-font-adjust,0pt))}}
.photo-tile{display:flex;flex-direction:column;justify-content:flex-start}.photo-tile img{flex:none}.photo-tile strong{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;font-weight:600}.photo-collage{grid-template-columns:repeat(auto-fill,minmax(220px,1fr))}

.photo-compact{table-layout:fixed;width:100%;min-width:1000px}.photo-compact th,.photo-compact td{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding:7px 8px;vertical-align:middle;height:38px}.photo-compact tbody tr:nth-child(even){background:#f0f3f5}.photo-compact tbody tr:hover{background:#e4f3f8}.photo-compact tbody tr{cursor:pointer}.photo-compact .photo-number-link{padding:0;border:0;background:none;color:inherit;font:inherit;cursor:pointer}.photo-compact .photo-more{padding:0;width:30px;height:26px;font-size:22px;line-height:1}.photo-menu{position:fixed;margin:0;width:150px;padding:6px;border:1px solid #bdccd3;border-radius:8px;box-shadow:0 5px 18px #0003;background:white;color:#163d50}.photo-menu .en-record-actions{display:grid;gap:3px}.photo-menu .btn{width:100%;text-align:left;background:white;color:#163d50;border:0}.photo-menu .btn:hover{background:#e4f3f8}
`;
