// Photo register uses the same project permissions and private R2 routes as project covers.
export const PHOTO_MODULE = String.raw`
var photoState={project:'',week:'',search:'',layout:'card',rows:[],busy:false,error:'',generation:0,user:null};
titles.photos=['Project Photos','Field photographs and reporting-week records'];
var photoNav=document.createElement('button');photoNav.className='nav-btn';photoNav.dataset.view='photos';photoNav.innerHTML='<span class="nav-icon">PH</span><span>Project Photos</span>';byId('adminNav').before(photoNav);
var photoPane=document.createElement('section');photoPane.className='pane';photoPane.dataset.pane='photos';photoPane.hidden=true;photoPane.innerHTML='<div id="photoToolbar" class="en-toolbar"></div><div id="photoContent" class="en-panel photo-content"></div>';byId('workspace').append(photoPane);
enBookIcon='<svg viewBox="0 0 28 28" aria-hidden="true"><path d="M4 3h21v23H4z" fill="#666"/><path d="M3 2h20v22H3z" fill="#c5c5c5" stroke="#777"/><path d="M5 4h16v8H5z" fill="#fff"/><path d="M5 15h16v7H5z" fill="#e5e5e5"/><path d="M8 18h10M8 20h8" stroke="#555"/><path d="M8 11c-3-2-3 7 0 5m6-5c-3-2-3 7 0 5m6-5c-3-2-3 7 0 5" fill="none" stroke="#444" stroke-width="1.6"/></svg>';
enPositionIcon=function(){return '<svg viewBox="0 0 28 28" aria-hidden="true"><path d="M5 2h13l5 5v16H5z" fill="#777"/><path d="M18 2v6h5" fill="#d8d8d8"/><path d="m9 10 4 4-4 4m5-8 4 4-4 4" fill="none" stroke="white"/><path d="M4 26h20" stroke="#777"/><circle cx="14" cy="26" r="2" fill="#087bbd"/></svg>'};
function photoProjects(){return state.projects.filter(function(p){return !state.unitScope||state.unitScope==='All'||p.business_unit===state.unitScope})}
function photoRows(){var q=photoState.search.toLowerCase();return photoState.rows.filter(function(p){return (!photoState.week||p.reporting_period===photoState.week)&&(!q||[p.caption,p.name,p.area,p.category,p.taken_by,p.id,p.notes].join(' ').toLowerCase().includes(q))})}
function photoFields(p){function input(key,label,type,max){return '<label>'+label+'<input name="'+key+'" type="'+(type||'text')+'" '+(max?'maxlength="'+max+'"':'')+' value="'+esc(p[key]||'')+'" '+(key==='reporting_period'?'required':'')+'></label>'}return '<div class="photo-fields">'+input('reporting_period','Reporting week','date')+input('date_taken','Date taken','date')+input('taken_by','Taken by','text',200)+input('area','Area','text',200)+input('category','Category','text',200)+'<label class="photo-wide">Description<textarea name="caption" maxlength="500" rows="3">'+esc(p.caption||'')+'</textarea></label><label class="photo-wide">Daily / conversation notes<textarea name="notes" maxlength="4000" rows="3">'+esc(p.notes||'')+'</textarea></label><label class="photo-check"><input name="include_in_report" type="checkbox" '+((p.include_in_report===0||p.include_in_report===false)?'':'checked')+'> Include in report</label></div>'}
function photoFormData(form){var data={};['reporting_period','date_taken','taken_by','area','category','caption','notes'].forEach(function(k){data[k]=form.elements[k].value});data.include_in_report=form.elements.include_in_report.checked;return data}
function photoNumber(p){return p.photo_number||'PH-'+p.id.slice(0,8).toUpperCase()}
function photoActions(p){return '<div class="en-record-actions"><button class="btn primary" data-photo-edit="'+p.id+'">Edit</button><button class="btn" data-photo-duplicate="'+p.id+'">Duplicate</button><button class="btn" data-photo-delete="'+p.id+'">Delete</button></div>'}
async function photoDelete(id){if(!canWrite())return;var p=photoState.rows.find(function(p){return p.id===id});if(!p||!confirm('Delete '+photoNumber(p)+'? This removes the photo and its details from the tracker.'))return;try{var result=await api('/api/projects/'+p.project_id+'/photos/'+id,{method:'DELETE'});await photoLoad();toast(result.cleanup_pending?'Photo removed. Storage cleanup needs administrator attention.':'Photo deleted.')}catch(e){toast(e.message)}}
function photoDraw(){
 if(!state.me)return;var projects=photoProjects(),rows=photoRows();if(!rows.some(function(p){return p.id===enhanced.selected.photos}))enhanced.selected.photos=rows[0]?.id||null;
 var periods=Array.from(new Set(photoState.rows.map(function(p){return p.reporting_period}).filter(Boolean))).sort().reverse();
 byId('photoToolbar').innerHTML='<div class="en-toolbar-top"><div><span class="en-eyebrow">Project Photos</span><strong>'+rows.length+' matching photos</strong></div><div class="en-layouts" aria-label="Photo view">'+['card','list','collage'].map(function(v){return '<button data-photo-layout="'+v+'" aria-pressed="'+(photoState.layout===v)+'">'+v[0].toUpperCase()+v.slice(1)+'</button>'}).join('')+'</div>'+(canWrite()?'<button class="btn primary" data-photo-upload>+ Add Photo</button>':'')+'</div><div class="photo-filters"><label>Project<select id="photoProject"><option value="">All accessible projects</option>'+projects.map(function(p){return '<option value="'+p.id+'" '+(String(p.id)===photoState.project?'selected':'')+'>'+esc((p.venue==='CENTRAL CITY'?'Central City — ':'')+p.name)+'</option>'}).join('')+'</select></label><label>Reporting week<select id="photoWeek"><option value="">All weeks</option>'+periods.map(function(w){return '<option '+(photoState.week===w?'selected':'')+'>'+esc(w)+'</option>'}).join('')+'</select></label><button class="btn photo-picker" data-en-picker data-tooltip="Rolodex/Pagination" aria-label="Rolodex/Pagination">'+(enhanced.navigator==='rolodex'?enBookIcon:enPositionIcon())+'</button><label>Search photos<input id="photoSearch" type="search" value="'+esc(photoState.search)+'" placeholder="Description, area, category…"></label><button class="btn" data-photo-refresh aria-label="Refresh photos">↻</button></div>';
 var host=byId('photoContent');if(photoState.busy){host.innerHTML='<p class="photo-notice" role="status">Loading photos…</p>';return}if(photoState.error){host.innerHTML='<p class="photo-notice" role="alert">'+esc(photoState.error)+'</p>';return}
 if(!rows.length){host.innerHTML='<div class="en-empty"><h2>No photos in this selection</h2><p>Select a project and upload photographs, or change your filters.</p>'+(canWrite()?'<button class="btn primary" data-photo-upload>+ Add Photo</button>':'')+'</div>';return}
 if(photoState.layout==='list')host.innerHTML='<div class="table-wrap"><table class="photo-table photo-compact"><colgroup><col style="width:125px"><col><col style="width:130px"><col style="width:150px"><col style="width:110px"><col style="width:120px"><col style="width:48px"></colgroup><thead><tr>'+['Photo No.','Description','Area','Category','Date taken','Taken by',''].map(function(x){return '<th>'+x+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(p){return '<tr data-photo-item="'+p.id+'" tabindex="0" '+(p.id===enhanced.selected.photos?'class="photo-selected"':'')+'><td><button class="photo-number-link" data-photo-open="'+p.id+'">'+photoNumber(p)+'</button></td><td title="'+esc(p.caption||'')+'">'+esc(p.caption||'—')+'</td><td title="'+esc(p.area||'')+'">'+esc(p.area||'—')+'</td><td title="'+esc(p.category||'')+'">'+esc(p.category||'—')+'</td><td>'+esc(p.date_taken||'—')+'</td><td>'+esc(p.taken_by||'—')+'</td><td>'+(canWrite()?'<button class="btn photo-more" aria-label="Actions for '+photoNumber(p)+'" popovertarget="photo-menu-'+p.id+'">⋯</button><div popover class="photo-menu" id="photo-menu-'+p.id+'">'+photoActions(p)+'</div>':'')+'</td></tr>'}).join('')+'</tbody></table></div>';
 else if(photoState.layout==='collage')host.innerHTML='<div class="photo-collage">'+rows.map(function(p){return '<button class="photo-tile" data-photo-open="'+p.id+'" data-photo-item="'+p.id+'"><img loading="lazy" src="'+enPhotoUrl(p.project_id,p.id)+'" alt="'+esc(p.caption||p.name)+'"><span><strong>'+esc(p.caption||photoNumber(p))+'</strong><small>'+esc(p.name)+' · '+esc(p.date_taken||p.reporting_period)+'</small></span></button>'}).join('')+'</div>';
 else {var p=rows.find(function(p){return p.id===enhanced.selected.photos});host.innerHTML='<article class="photo-record" data-photo-item="'+p.id+'"><figure><a target="_blank" rel="noopener" href="'+enPhotoUrl(p.project_id,p.id)+'"><img src="'+enPhotoUrl(p.project_id,p.id)+'" alt="'+esc(p.caption||p.name)+'"></a><figcaption>'+photoNumber(p)+'</figcaption></figure><div><span class="en-eyebrow">'+esc(p.business_unit)+'</span><h2>'+esc(p.name)+'</h2><dl class="photo-details">'+[['Photo number',photoNumber(p)],['Date taken',p.date_taken],['Taken by',p.taken_by],['Area',p.area],['Category',p.category],['Reporting week',p.reporting_period],['Description',p.caption],['Include in report',p.include_in_report?'Yes':'No'],['Daily / conversation notes',p.notes]].map(function(v){return '<div><dt>'+v[0]+'</dt><dd>'+esc(v[1]||'Not recorded')+'</dd></div>'}).join('')+'</dl>'+(canWrite()?photoActions(p):'')+'</div></article>'}
}
async function photoLoad(){if(!state.me)return;var generation=++photoState.generation,session=enSession;photoState.busy=true;photoState.error='';photoState.rows=[];photoDraw();var projects=photoProjects().filter(function(p){return !photoState.project||String(p.id)===photoState.project}),rows=[];
 try{for(var start=0;start<projects.length;start+=5){await Promise.all(projects.slice(start,start+5).map(async function(p){var data=await api('/api/projects/'+p.id+'/photos');rows.push(...data.photos.filter(function(f){return f.kind==='progress'}).map(function(f){return Object.assign({},f,{project_id:p.id,name:(p.venue==='CENTRAL CITY'?'Central City — ':'')+p.name,business_unit:p.business_unit})}))}));if(generation!==photoState.generation||session!==enSession)return}rows.sort(function(a,b){return String(b.reporting_period).localeCompare(String(a.reporting_period))||String(b.created_at).localeCompare(String(a.created_at))});photoState.rows=rows}catch(e){if(generation!==photoState.generation||session!==enSession)return;photoState.rows=[];photoState.error=e.message}photoState.busy=false;photoDraw();enhancedExtras();}
function photoEdit(id){if(!canWrite())return;var p=photoState.rows.find(function(p){return p.id===id});if(!p)return;var d=enDialog('Edit photo — '+photoNumber(p),photoFields(p));d.querySelector('form').onsubmit=async function(e){e.preventDefault();var b=d.querySelector('[type=submit]');b.disabled=true;try{var data=photoFormData(e.target);data.revision=p.revision||0;await api('/api/projects/'+p.project_id+'/photos/'+p.id,{method:'PATCH',body:JSON.stringify(data)});d.close();await photoLoad();toast('Photo details saved.')}catch(e){d.querySelector('.en-form-error').textContent=e.message}finally{b.disabled=false}}}
function photoInitials(){var profile=state.me.profile||{},name=[profile.first_name,profile.last_name].filter(Boolean).join(' ')||state.me.name||state.me.email.split('@')[0].replace(/[._-]/g,' ');return name.split(/\s+/).map(function(n){return n[0]||''}).join('').replace(/[^a-z]/gi,'').slice(0,4).toUpperCase()||'USR'}
function photoUpload(copy){if(!canWrite())return;var projects=photoProjects(),today=new Date().toISOString().slice(0,10),d=enDialog('Upload project photos','<label>User initials<input name="photo_initials" maxlength="4" pattern="[A-Za-z]{1,4}" required value="'+photoInitials()+'"></label><p class="photo-number-status" aria-live="polite">Photo number: initials–date–01…99, assigned on save.</p><label>Project<select name="project" required><option value="">Choose project…</option>'+projects.map(function(p){return '<option value="'+p.id+'" '+(String(p.id)===photoState.project?'selected':'')+'>'+esc((p.venue==='CENTRAL CITY'?'Central City — ':'')+p.name)+'</option>'}).join('')+'</select></label><div class="photo-upload-actions"><label class="btn">Photo Library<input class="photo-file" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="btn">Take Photo<input class="photo-camera" type="file" accept="image/*" capture="environment"></label></div><p class="photo-selection">Choose one or more photos. The details below apply to this batch; each photo can be edited afterward.</p><div class="en-upload-preview"></div>'+photoFields(copy?Object.assign({},copy,{caption:''}):{reporting_period:photoState.week||today,date_taken:today,taken_by:state.me.name||state.me.email,include_in_report:1})),files=[],urls=[];
 if(copy)d.querySelector('[name=project]').value=String(copy.project_id);
 var next=document.createElement('button');next.type='submit';next.className='btn primary';next.dataset.photoNext='true';next.textContent='Save & Take Next';d.querySelector('[type=submit]').before(next);d.querySelector('[type=submit]:not([data-photo-next])').textContent='Save & Close';
 function select(e){files=Array.from(new Map(files.concat(Array.from(e.target.files)).map(function(f){return [f.name+'|'+f.size+'|'+f.lastModified,f]})).values());urls.forEach(URL.revokeObjectURL);urls=files.map(function(f){return URL.createObjectURL(f)});d.querySelector('.en-upload-preview').innerHTML=urls.map(function(u){return '<img src="'+u+'" alt="Selected photo">'}).join('');d.querySelector('.photo-selection').textContent=files.length+' selected photo(s)';}d.querySelectorAll('[type=file]').forEach(function(input){input.onchange=select});d.addEventListener('close',function(){urls.forEach(URL.revokeObjectURL)});
 d.querySelector('form').onsubmit=async function(e){e.preventDefault();var form=e.target,buttons=Array.from(form.querySelectorAll('[type=submit]')),continueSeries=!!e.submitter?.hasAttribute('data-photo-next'),saved=0,lastNumber='';if(!files.length){form.querySelector('.en-form-error').textContent='Choose photos first.';return}buttons.forEach(function(b){b.disabled=true});form.querySelector('.en-form-error').textContent='';try{var metadata=photoFormData(form),pid=form.elements.project.value;metadata.photo_initials=form.elements.photo_initials.value.toUpperCase();for(var file of files){var photo=await photoPrepare(file),q=new URLSearchParams({kind:'progress',period:metadata.reporting_period,caption:metadata.caption});var result=await api('/api/projects/'+pid+'/photos?'+q,{method:'POST',headers:{'content-type':photo.type,'x-photo-metadata':encodeURIComponent(JSON.stringify(metadata))},body:photo});lastNumber=result.photo_number||'';saved++}photoState.project=pid;photoState.week=metadata.reporting_period;photoState.search='';if(continueSeries){files=[];urls.forEach(URL.revokeObjectURL);urls=[];form.querySelectorAll('[type=file]').forEach(function(input){input.value=''});form.elements.caption.value='';form.querySelector('.en-upload-preview').replaceChildren();var n=Number(lastNumber.slice(-2));form.querySelector('.photo-number-status').textContent='Saved '+lastNumber+(n<99?' · Next: '+lastNumber.slice(0,-2)+String(n+1).padStart(2,'0')+' (confirmed on save)':' · 99-photo limit reached for these initials/date.');form.querySelector('.photo-selection').textContent='Ready for the next photo. Project and details retained; image and description cleared.';form.querySelector('.photo-camera').focus();}else d.close();await photoLoad();toast(saved+' photo(s) saved.')}catch(e){files=files.slice(saved);form.querySelector('.en-form-error').textContent=(saved?saved+' photo(s) saved; retry will upload only the remaining files. ':'')+e.message}finally{buttons.forEach(function(b){b.disabled=false})}};
}
async function photoPrepare(file){
 if(file.size>30*1024*1024)throw Error('Choose photos under 30 MB.');
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use JPG, PNG or WebP. For HEIC photos, export as JPEG or use the camera’s Most Compatible format.');
 if(file.size<=5*1024*1024)return file;
 var u=URL.createObjectURL(file);try{var img=new Image();img.src=u;await img.decode();var scale=Math.min(1,2400/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);var blob=await new Promise(function(resolve){canvas.toBlob(resolve,'image/jpeg',.86)});if(!blob||blob.size>5*1024*1024)throw Error('Photo is too large; choose a smaller copy.');return blob}finally{URL.revokeObjectURL(u)}
}
var photoOldRows=enhancedRows;enhancedRows=function(m){return m==='photos'?photoRows():photoOldRows(m)};
var photoOldModule=enhancedCurrentModule;enhancedCurrentModule=function(){return location.hash==='#photos'?'photos':photoOldModule()};
var photoOldBring=enhancedBringIntoView;enhancedBringIntoView=function(){if(location.hash!=='#photos')return photoOldBring();var item=photoPane.querySelector('[data-photo-item="'+enhanced.selected.photos+'"]');if(item)item.scrollIntoView({block:'nearest'})};
var photoOldRender=renderEnhanced;renderEnhanced=function(){photoOldRender();if(!state.me)return;if(photoState.user!==state.me.email){photoState.user=state.me.email;photoState.rows=[];photoState.project='';photoState.week='';photoState.search='';photoState.error='';photoState.generation++}if(location.hash==='#photos')photoDraw()};
var photoOldView=setView;setView=function(view,keep){var entering=location.hash!=='#photos';photoOldView(view,keep);byId('addBtn').hidden=view==='photos'||!canWrite();if(view==='photos'){if(entering){photoState.project=String(enhanced.selected.projects||'');photoState.week='';photoState.search=''}photoLoad()}};
var photoOldSignout=showSignIn;showSignIn=function(m){photoState.generation++;photoState.rows=[];photoState.user=null;byId('photoContent').replaceChildren();byId('photoToolbar').replaceChildren();return photoOldSignout(m)};
document.addEventListener('dblclick',function(e){var row=e.target.closest('.photo-compact tr[data-photo-item]');if(!row||e.target.closest('button,[popover]'))return;enhanced.selected.photos=row.dataset.photoItem;photoState.layout='card';photoDraw();enhancedExtras()});
document.addEventListener('keydown',function(e){if(e.key!=='Enter'||!e.target.matches('.photo-compact tr[data-photo-item]'))return;enhanced.selected.photos=e.target.dataset.photoItem;photoState.layout='card';photoDraw();enhancedExtras()});
document.addEventListener('click',function(e){var b=e.target.closest('.photo-more');if(b){var m=document.getElementById(b.getAttribute('popovertarget')),r=b.getBoundingClientRect();m.style.left=Math.max(8,r.right-150)+'px';m.style.top=Math.max(8,Math.min(r.bottom+4,innerHeight-150))+'px'}var m=e.target.closest('.photo-menu');if(m&&e.target.closest('button'))m.hidePopover()});
document.addEventListener('click',function(e){var b=e.target.closest('[data-photo-layout],[data-photo-open],[data-photo-edit],[data-photo-duplicate],[data-photo-delete],[data-photo-upload],[data-photo-refresh]');if(!b)return;if(b.dataset.photoLayout){photoState.layout=b.dataset.photoLayout;photoDraw();enhancedExtras()}else if(b.dataset.photoOpen){enhanced.selected.photos=b.dataset.photoOpen;photoState.layout='card';photoDraw();enhancedExtras()}else if(b.dataset.photoEdit)photoEdit(b.dataset.photoEdit);else if(b.dataset.photoDuplicate)photoUpload(photoState.rows.find(function(p){return p.id===b.dataset.photoDuplicate}));else if(b.dataset.photoDelete)photoDelete(b.dataset.photoDelete);else if(b.hasAttribute('data-photo-upload'))photoUpload();else photoLoad()});
document.addEventListener('change',function(e){if(e.target.id==='photoProject'){photoState.project=e.target.value;photoState.week='';photoLoad()}if(e.target.id==='photoWeek'){photoState.week=e.target.value;photoDraw();enhancedExtras()}});
document.addEventListener('input',function(e){if(e.target.id==='photoSearch'){var pos=e.target.selectionStart;photoState.search=e.target.value;photoDraw();enhancedExtras();byId('photoSearch').focus();try{byId('photoSearch').setSelectionRange(pos,pos)}catch{}}});
document.addEventListener('click',function(e){if(e.target.closest('[data-business-unit]')&&location.hash==='#photos'){photoState.project='';photoState.week='';photoLoad()}});
`;
