export const PHOTO_DROP = String.raw`
function enAcceptDrop(files,multiple){var list=Array.from(files||[]);if(!list.length)return null;if(!multiple&&list.length!==1){toast('Drop one image to replace the main project photo.');return null}if(list.some(function(f){return !['image/jpeg','image/png','image/webp'].includes(f.type)})){toast('Please use JPG, PNG or WebP images.');return null}return list}
function enDropToInput(input,files){var dt=new DataTransfer();files.forEach(function(f){dt.items.add(f)});input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}
function enWireDrop(d,input,multiple){if(!d||!input||d.querySelector('.en-attachment-drop'))return;var zone=document.createElement('div');zone.className='en-attachment-drop';zone.tabIndex=0;zone.setAttribute('role','button');zone.setAttribute('aria-label',multiple?'Choose or drop project photos':'Choose or drop a main project photo');zone.innerHTML='<strong>＋ '+(multiple?'Drop photos here':'Drop one project photo here')+'</strong><span>or click to browse · JPG, PNG, WebP</span>';d.querySelector('h2').after(zone);function choose(){input.click()}zone.onclick=choose;zone.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};d.addEventListener('dragover',function(e){if(Array.from(e.dataTransfer.types).includes('Files')){e.preventDefault();zone.classList.add('is-dragging')}});d.addEventListener('dragleave',function(e){if(!d.contains(e.relatedTarget))zone.classList.remove('is-dragging')});d.addEventListener('drop',function(e){e.preventDefault();e.stopPropagation();zone.classList.remove('is-dragging');if(d.querySelector('[type=submit]').disabled)return;var files=enAcceptDrop(e.dataTransfer.files,multiple);if(files)enDropToInput(input,files)})}
var enDropUpload=enUpload;enUpload=function(pid,kind,files){if(files&&!enAcceptDrop(files,kind==='progress'))return;enDropUpload(pid,kind,files);var d=Array.from(document.querySelectorAll('.en-workflow-dialog')).at(-1);enWireDrop(d,d&&d.querySelector('[type=file]'),kind==='progress')};
var photoDropUpload=photoUpload;photoUpload=function(copy,files){photoDropUpload(copy);var d=Array.from(document.querySelectorAll('.en-workflow-dialog')).at(-1);enWireDrop(d,d&&d.querySelector('.photo-file'),true);if(files&&d){var valid=enAcceptDrop(files,true);if(valid)enDropToInput(d.querySelector('.photo-file'),valid)}};
document.addEventListener('dragover',function(e){if(!Array.from(e.dataTransfer.types).includes('Files'))return;e.preventDefault();var target=e.target.closest('.en-record [data-en-cover],#photoContent');if(target&&canWrite())target.classList.add('en-file-hover')});
document.addEventListener('dragleave',function(e){var target=e.target.closest('.en-file-hover');if(target&&!target.contains(e.relatedTarget))target.classList.remove('en-file-hover')});
document.addEventListener('drop',function(e){if(!e.dataTransfer.files.length)return;e.preventDefault();document.querySelectorAll('.en-file-hover').forEach(function(x){x.classList.remove('en-file-hover')});if(e.target.closest('dialog'))return;if(!canWrite())return toast('Photo uploads require Editor access.');var cover=e.target.closest('.en-record [data-en-cover]');if(cover)return enUpload(cover.dataset.enCover,'cover',e.dataTransfer.files);if(e.target.closest('#photoContent'))return photoUpload(null,e.dataTransfer.files)});
`;
