// Synthetic evaluation data only. No live Delaware North records are included.
export const SEED_PROJECTS = [
  {
    source_key: "Sample:Corporate:Office Refresh:S-1001",
    business_unit: "Corporate", venue: "Sample Headquarters", project_type: "Capital",
    name: "Office Refresh", capp_number: "S-1001", initiative_number: null,
    project_manager: "Sample Project Manager", development_lead: null,
    status: "Active", phase: "Construction / Delivery",
    scope_description: "Synthetic interior renovation record for code review.",
    current_update: "Sample update: finishes are in progress and the schedule remains on track.",
    previous_update: "Sample update: construction mobilization completed.",
    budget_risk: "Low", schedule_risk: "Low", precon_capp: 25000,
    construction_capp: 475000, add_capp: 10000, approved_budget: 510000,
    anticipated_final_cost: 498000, original_start_date: "2026-07-01",
    current_start_date: "2026-07-01", original_turnover_date: "2026-11-15",
    current_turnover_date: "2026-11-15", duration_change_days: 0,
    reporting_period: "2026-09-04"
  },
  {
    source_key: "Sample:Gaming:Guest Area:S-1002",
    business_unit: "Gaming", venue: "Sample Resort", project_type: "Capital",
    name: "Guest Area Renovation", capp_number: "S-1002", initiative_number: null,
    project_manager: "Sample Project Manager", development_lead: null,
    status: "Active", phase: "Design",
    scope_description: "Synthetic guest-area renovation record for code review.",
    current_update: "Sample update: design coordination identified one schedule issue for resolution.",
    previous_update: "Sample update: design package issued for review.",
    budget_risk: "Medium", schedule_risk: "High", precon_capp: 80000,
    construction_capp: 920000, add_capp: 0, approved_budget: 1000000,
    anticipated_final_cost: 1045000, original_start_date: "2026-10-01",
    current_start_date: "2026-10-15", original_turnover_date: "2027-03-01",
    current_turnover_date: "2027-03-22", duration_change_days: 21,
    reporting_period: "2026-09-04"
  },
  {
    source_key: "Sample:Parks:Food Service:S-1003",
    business_unit: "Parks & Resorts", venue: "Sample Park", project_type: "Capital",
    name: "Food Service Upgrade", capp_number: "S-1003", initiative_number: null,
    project_manager: "Sample Project Manager", development_lead: null,
    status: "Closeout", phase: "Closeout",
    scope_description: "Synthetic food-service improvement record for code review.",
    current_update: "Sample update: punch-list work is complete and closeout documents are being assembled.",
    previous_update: "Sample update: final inspection completed.",
    budget_risk: "Low", schedule_risk: "Low", precon_capp: 15000,
    construction_capp: 285000, add_capp: 5000, approved_budget: 305000,
    anticipated_final_cost: 302500, original_start_date: "2026-03-15",
    current_start_date: "2026-03-15", original_turnover_date: "2026-08-15",
    current_turnover_date: "2026-08-20", duration_change_days: 5,
    reporting_period: "2026-09-04"
  },
  {
    source_key: "Sample:Travel:Terminal:S-1004",
    business_unit: "Travel Hospitality", venue: "Sample Terminal", project_type: "Capital",
    name: "Concession Modernization", capp_number: "S-1004", initiative_number: null,
    project_manager: "Sample Project Manager", development_lead: null,
    status: "On Hold", phase: "Preconstruction",
    scope_description: "Synthetic concession modernization record for code review.",
    current_update: "Sample update: project is paused pending landlord approval.",
    previous_update: "Sample update: preliminary estimate received.",
    budget_risk: "Medium", schedule_risk: "Medium", precon_capp: 45000,
    construction_capp: 655000, add_capp: null, approved_budget: 700000,
    anticipated_final_cost: 730000, original_start_date: "2026-12-01",
    current_start_date: null, original_turnover_date: "2027-05-01",
    current_turnover_date: null, duration_change_days: null,
    reporting_period: "2026-09-04"
  },
  {
    source_key: "Sample:Development:New Concept:S-D001",
    business_unit: "Corporate", venue: "Development Pipeline", project_type: "Development",
    name: "New Venue Concept", capp_number: null, initiative_number: "S-D001",
    project_manager: null, development_lead: "Sample Development Lead",
    status: "Active", phase: "Development",
    scope_description: "Synthetic development-pipeline record for code review.",
    current_update: "Sample update: feasibility review is underway.", previous_update: null,
    budget_risk: "Not Rated", schedule_risk: "Not Rated", precon_capp: null,
    construction_capp: null, add_capp: null, approved_budget: null,
    anticipated_final_cost: null, original_start_date: null, current_start_date: null,
    original_turnover_date: null, current_turnover_date: null, duration_change_days: null,
    reporting_period: "2026-09-04", request_date: "2026-08-20",
    requestor: "Sample Requestor", deliverable_due_date: "2026-10-15",
    consultants: "Sample Consultant", food_service_design: "To be determined",
    design_capp: "Under review", subsidiary_expense_total: 12000,
    original_estimate: 1500000, original_estimate_date: "2026-08-25",
    current_estimate: 1580000, current_estimate_date: "2026-09-04", source_row: 1
  }
];
