const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/tmp/dn-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1536,height:1040}}),errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});
await page.goto('file://'+process.cwd()+'/deliverables/DN_Tracker_Enhanced_Interactive_Demo.html');await page.locator('#enPanel-projects .en-record').waitFor();assert.equal(await page.evaluate(()=>enhanced.navigator),'rolodex');assert.equal(await page.locator('[data-en-meeting]').count(),0);assert.equal(await page.locator('.en-nav-menu').count(),0);
const picker=page.locator('#projectsControls [data-en-picker]'),icons=[];for(const nav of ['strip','slider','rolodex']){icons.push(await picker.innerHTML());await picker.click();assert.equal(await page.evaluate(()=>enhanced.navigator),nav)}assert.equal(new Set(icons).size,3);assert.ok((await picker.getAttribute('data-tooltip')).includes('Rolodex'));
const base=await page.locator('#enPanel-projects .en-record h2').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));await page.locator('#projectsControls [data-en-font="1"]').click();const larger=await page.locator('#enPanel-projects .en-record h2').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));assert.ok(Math.abs(larger-base-1.333)<.03);await page.locator('#enToggle').click();assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--en-font-adjust').trim()),'1pt');await page.locator('#enToggle').click();await page.locator('#projectsControls [data-en-font="-1"]').click();
await page.locator('#enPanel-projects [data-en-upload=cover]').click();await page.locator('.en-workflow-dialog [type=file]').setInputFiles('assets/delaware-north-logo.png');await page.locator('.en-caption').fill('Demo property picture');await page.locator('.en-workflow-dialog [type=submit]').click();await page.locator('.en-workflow-dialog').waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('.en-photo img')?.src.startsWith('blob:'));assert.ok(await page.locator('#enPanel-projects .en-photo img').evaluate(el=>el.complete&&el.naturalWidth>0));
await page.locator('#enPanel-projects [data-en-save-current] textarea').fill('Demo saved activity');await page.locator('#enPanel-projects [data-en-save-current] [type=submit]').click();await page.waitForFunction(()=>state.projects.find(p=>p.id===enhanced.selected.projects)?.current_update==='Demo saved activity');
await page.locator('#enToolbar-projects [data-en-layout=collage]').click();await page.locator('[data-en-upload=progress]').first().click();await page.locator('.en-workflow-dialog [type=file]').setInputFiles('assets/delaware-north-logo.png');await page.locator('.en-workflow-dialog [type=submit]').click();await page.locator('.en-workflow-dialog').waitFor({state:'detached'});await page.locator('#enPanel-projects .en-week-grid img').waitFor();assert.ok((await page.locator('#enPanel-projects .en-week-grid img').getAttribute('src')).startsWith('blob:'));
await page.reload();await page.locator('#enPanel-projects .en-record').waitFor();assert.notEqual(await page.locator('#enPanel-projects [data-en-save-current] textarea').inputValue(),'Demo saved activity');assert.equal(await page.locator('.en-photo img[src^="blob:"]').count(),0);await page.screenshot({path:'qa/interactive-demo.png'});assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);await browser.close();console.log('PASS: interactive file demo, uploads/images/activity, reload reset, zero remote requests, 3 cycling icons/default, tooltips, A controls across Classic/Enhanced, Meeting removed.');})().catch(e=>{console.error(e);process.exit(1)});
