const {chromium}=require('playwright'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const server=spawn(process.execPath,['scripts/preview-enhanced.mjs'],{stdio:['ignore','pipe','inherit']});
(async()=>{await new Promise((r,j)=>{server.stdout.on('data',d=>{if(String(d).includes('Local preview'))r()});server.on('error',j)});const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const p=await b.newPage({viewport:{width:1536,height:960}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173');await p.locator('#workspace').waitFor({state:'visible'});
const width=await p.locator('.sidebar').evaluate(x=>x.getBoundingClientRect().width);assert.equal(width,224);
async function freeze(){const th=p.locator('#projectsHead th').first(),y=await th.evaluate(x=>x.getBoundingClientRect().top);await p.locator('[data-pane=projects] .table-wrap').evaluate(x=>x.scrollTop=500);assert.ok(Math.abs((await th.evaluate(x=>x.getBoundingClientRect().top))-y)<2);assert.equal(await p.evaluate(()=>scrollY),0);await p.locator('[data-pane=projects] .table-wrap').evaluate(x=>x.scrollTop=0)}
await freeze();await p.locator('#enToggle').click();assert.equal(await p.locator('.sidebar').evaluate(x=>x.getBoundingClientRect().width),width);await freeze();
await p.locator('#enToolbar-projects [data-en-layout=record]').click();await p.locator('#projectsControls [data-en-picker]').click();await p.locator('#projectsControls [data-en-choice=rolodex]').click();await p.locator('#enRolodex').waitFor({state:'visible'});assert.equal(await p.locator('#enRolodex').evaluate(x=>x.previousElementSibling.dataset.view),'portfolio');
assert.equal(await p.locator('#enToggle span').last().textContent(),'Classic');assert.equal(await p.locator('#enToggle').evaluate(x=>getComputedStyle(x).borderTopWidth),'0px');const ro=await p.locator('#enRolodex').boundingBox();assert.ok(ro.width>125&&ro.width<145);assert.ok(Math.abs(ro.x+ro.width/2-112)<3);assert.equal(await p.locator('.risk-low').first().evaluate(x=>getComputedStyle(x).color),'rgb(255, 255, 255)');
const first=await p.locator('#enRolodex [data-en-position]').inputValue();await p.locator('.en-book-forward').click();assert.equal(Number(await p.locator('#enRolodex [data-en-position]').inputValue()),Number(first)+1);await p.locator('.en-book-back').click();assert.equal(await p.locator('#enRolodex [data-en-position]').inputValue(),first);
const track=p.locator('#enRolodex [data-en-slider]');const box=await track.boundingBox();await p.mouse.click(box.x+box.width/2,box.y+box.height*.75);assert.ok(Number(await p.locator('#enRolodex [data-en-position]').inputValue())>2);const positionBefore=Number(await p.locator('#enRolodex [data-en-position]').inputValue());await p.mouse.move(box.x+box.width/2,box.y+box.height*.75);await p.mouse.down();await p.mouse.move(box.x+box.width/2,box.y+box.height*.25,{steps:8});await p.mouse.up();assert.ok(Number(await p.locator('#enRolodex [data-en-position]').inputValue())<positionBefore);
await p.locator('#enRolodex [data-en-position]').fill('1');await p.locator('#enRolodex [data-en-position]').press('Enter');await p.locator('#enRolodex [data-en-position]').blur();
await p.screenshot({path:'qa/revision-rolodex.png'});
await p.locator('#projectsControls [data-en-picker]').click();await p.locator('#projectsControls [data-en-choice=slider]').click();const bottom=await p.locator('#enBottomNav').boundingBox();assert.ok(Math.abs(bottom.y+bottom.height-960)<2);await p.locator('#enBottomNav [data-en-position]').fill('3');await p.locator('#enBottomNav [data-en-position]').press('Enter');await p.locator('#enBottomNav [data-en-position]').blur();assert.equal(await p.locator('#enBottomNav [data-en-position]').inputValue(),'3');
await p.screenshot({path:'qa/revision-pagination.png'});
await p.locator('#enToolbar-projects [data-en-layout=list]').click();await freeze();await p.locator('#refreshBtn').hover();await p.locator('#instantTooltip').waitFor({state:'visible'});assert.equal(await p.locator('#instantTooltip').evaluate(x=>getComputedStyle(x,':before').content),'""');await p.screenshot({path:'qa/revision-list.png'});
assert.ok((await p.locator('.risk-low').first().evaluate(x=>getComputedStyle(x).backgroundColor)).includes('0.7'));
await p.setViewportSize({width:1050,height:800});assert.equal(await p.locator('.sidebar').evaluate(x=>x.getBoundingClientRect().width),86);await p.locator('#enToggle').click();assert.equal(await p.locator('.sidebar').evaluate(x=>x.getBoundingClientRect().width),86);await p.locator('#enToggle').click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:'qa/revision-mobile.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await b.close();server.kill();console.log('PASS: shared responsive sidebar, Classic/Enhanced frozen headers, Rolodex placement/card/arrows/track/number, bottom paginator, tooltip pointer, 70% risk fills, mobile width')})().catch(e=>{console.error(e);server.kill();process.exit(1)});
